export interface ETFHolding {
  ticker: string
  name: string
  weight: number
  sector?: string
}

export interface ETFPerformance {
  oneMonth: number
  threeMonth: number
  sixMonth: number
  ytd: number
  oneYear: number
  threeYear: number | null
  fiveYear: number | null
  tenYear: number | null
  sinceInception: number
}

export interface SectorAllocation {
  sector: string
  weight: number
}

export interface Broker {
  name: string
  countries: string[]
  url: string
  commission?: string
}

export interface ETF {
  ticker: string
  name: string
  focus: string
  listing: string
  listingFlag: string
  expenseRatio: number
  aum: string
  inceptionDate: string
  provider: string
  benchmark: string
  description: string
  holdings: ETFHolding[]
  performance: ETFPerformance
  sectorAllocation: SectorAllocation[]
  distributionYield: number
  turnoverRate: number
  esgRating?: string
  shariahCertification: string
  riskLevel: "Low" | "Moderate" | "High"
  investorType: string
  top10Concentration?: number
  brokers?: Broker[]
  prospectusUrl?: string
}

export const etfData: ETF[] = [
  {
    ticker: "SPUS",
    name: "SP Funds S&P 500 Sharia Industry Exclusions ETF",
    focus: "US Large Cap Growth",
    listing: "US",
    listingFlag: "US",
    expenseRatio: 0.45,
    aum: "$2.0B",
    inceptionDate: "Dec 17, 2019",
    provider: "SP Funds",
    benchmark: "S&P 500 Shariah Industry Exclusions Index",
    description: "The largest Halal ETF in the US. SPUS provides value-focused exposure to approximately 200 Sharia-compliant stocks from the S&P 500 Index, focusing on companies with low leverage and strong financial health. Ideal for investors seeking core US large-cap exposure.",
    riskLevel: "Moderate",
    investorType: "Core US Equity Allocation",
    holdings: [
      { ticker: "NVDA", name: "NVIDIA Corporation", weight: 14.07, sector: "Technology" },
      { ticker: "AAPL", name: "Apple Inc", weight: 12.28, sector: "Technology" },
      { ticker: "MSFT", name: "Microsoft Corporation", weight: 10.78, sector: "Technology" },
      { ticker: "GOOGL", name: "Alphabet Inc Class A", weight: 5.62, sector: "Technology" },
      { ticker: "AVGO", name: "Broadcom Inc", weight: 5.03, sector: "Technology" },
      { ticker: "TSLA", name: "Tesla Inc", weight: 3.77, sector: "Consumer Cyclical" },
      { ticker: "LLY", name: "Eli Lilly and Company", weight: 2.63, sector: "Healthcare" },
      { ticker: "XOM", name: "Exxon Mobil Corporation", weight: 1.59, sector: "Energy" },
      { ticker: "JNJ", name: "Johnson & Johnson", weight: 1.53, sector: "Healthcare" },
      { ticker: "ABBV", name: "AbbVie Inc", weight: 1.24, sector: "Healthcare" },
      { ticker: "UNH", name: "UnitedHealth Group Inc", weight: 1.18, sector: "Healthcare" },
      { ticker: "CVX", name: "Chevron Corporation", weight: 1.12, sector: "Energy" },
      { ticker: "PG", name: "Procter & Gamble Co", weight: 1.08, sector: "Consumer Staples" },
      { ticker: "MRK", name: "Merck & Co Inc", weight: 1.02, sector: "Healthcare" },
      { ticker: "AMD", name: "Advanced Micro Devices", weight: 0.98, sector: "Technology" },
      { ticker: "COST", name: "Costco Wholesale Corp", weight: 0.95, sector: "Consumer Staples" },
      { ticker: "PEP", name: "PepsiCo Inc", weight: 0.92, sector: "Consumer Staples" },
      { ticker: "ADBE", name: "Adobe Inc", weight: 0.88, sector: "Technology" },
      { ticker: "CRM", name: "Salesforce Inc", weight: 0.85, sector: "Technology" },
      { ticker: "NFLX", name: "Netflix Inc", weight: 0.82, sector: "Communication" },
    ],
    performance: {
      oneMonth: -0.41,
      threeMonth: 3.50,
      sixMonth: 15.48,
      ytd: 19.77,
      oneYear: 19.77,
      threeYear: 26.70,
      fiveYear: 16.38,
      tenYear: null,
      sinceInception: 17.98,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 48.5 },
      { sector: "Healthcare", weight: 13.2 },
      { sector: "Consumer Cyclical", weight: 10.8 },
      { sector: "Energy", weight: 7.5 },
      { sector: "Industrials", weight: 8.2 },
      { sector: "Consumer Staples", weight: 5.3 },
      { sector: "Other", weight: 6.5 },
    ],
    distributionYield: 0.44,
    turnoverRate: 5,
    esgRating: "AA",
    shariahCertification: "AAOIFI Certified",
    top10Concentration: 58.08,
    prospectusUrl: "https://www.sp-funds.com/spus/",
    brokers: [
      { name: "Fidelity", countries: ["US"], url: "https://www.fidelity.com", commission: "$0" },
      { name: "Charles Schwab", countries: ["US"], url: "https://www.schwab.com", commission: "$0" },
      { name: "Interactive Brokers", countries: ["US", "UK", "CA", "EU"], url: "https://www.interactivebrokers.com", commission: "$0-$1" },
      { name: "TD Ameritrade", countries: ["US"], url: "https://www.tdameritrade.com", commission: "$0" },
    ],
  },
  {
    ticker: "HLAL",
    name: "Wahed FTSE USA Shariah ETF",
    focus: "US Large Cap Growth",
    listing: "US",
    listingFlag: "US",
    expenseRatio: 0.50,
    aum: "$730M",
    inceptionDate: "Jul 16, 2019",
    provider: "Wahed Invest",
    benchmark: "FTSE Shariah USA Index",
    description: "One of the original US Halal ETFs. HLAL tracks the FTSE Shariah USA Index, providing exposure to large- and mid-cap US companies that are Shariah-compliant. Yasaar Limited audits the ETF quarterly. Good for investors wanting broad US market exposure.",
    holdings: [
      { ticker: "AAPL", name: "Apple Inc", weight: 15.20, sector: "Technology" },
      { ticker: "MSFT", name: "Microsoft Corporation", weight: 12.80, sector: "Technology" },
      { ticker: "META", name: "Meta Platforms Inc", weight: 8.50, sector: "Technology" },
      { ticker: "GOOGL", name: "Alphabet Inc Class A", weight: 7.20, sector: "Technology" },
      { ticker: "TSLA", name: "Tesla Inc", weight: 5.80, sector: "Consumer Cyclical" },
      { ticker: "NVDA", name: "NVIDIA Corporation", weight: 5.40, sector: "Technology" },
      { ticker: "AVGO", name: "Broadcom Inc", weight: 3.20, sector: "Technology" },
      { ticker: "XOM", name: "Exxon Mobil Corporation", weight: 2.80, sector: "Energy" },
      { ticker: "JNJ", name: "Johnson & Johnson", weight: 2.50, sector: "Healthcare" },
      { ticker: "PG", name: "Procter & Gamble Co", weight: 2.10, sector: "Consumer Staples" },
      { ticker: "LLY", name: "Eli Lilly and Company", weight: 1.95, sector: "Healthcare" },
      { ticker: "UNH", name: "UnitedHealth Group Inc", weight: 1.88, sector: "Healthcare" },
      { ticker: "HD", name: "Home Depot Inc", weight: 1.72, sector: "Consumer Cyclical" },
      { ticker: "CVX", name: "Chevron Corporation", weight: 1.65, sector: "Energy" },
      { ticker: "ABBV", name: "AbbVie Inc", weight: 1.58, sector: "Healthcare" },
      { ticker: "MRK", name: "Merck & Co Inc", weight: 1.45, sector: "Healthcare" },
      { ticker: "COST", name: "Costco Wholesale Corp", weight: 1.38, sector: "Consumer Staples" },
      { ticker: "AMD", name: "Advanced Micro Devices", weight: 1.32, sector: "Technology" },
      { ticker: "PEP", name: "PepsiCo Inc", weight: 1.25, sector: "Consumer Staples" },
      { ticker: "CRM", name: "Salesforce Inc", weight: 1.18, sector: "Technology" },
    ],
    performance: {
      oneMonth: -0.35,
      threeMonth: 3.85,
      sixMonth: 14.92,
      ytd: 18.45,
      oneYear: 18.45,
      threeYear: 24.80,
      fiveYear: 15.20,
      tenYear: null,
      sinceInception: 16.50,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 43.0 },
      { sector: "Healthcare", weight: 13.0 },
      { sector: "Communication Services", weight: 12.0 },
      { sector: "Consumer Cyclical", weight: 9.5 },
      { sector: "Energy", weight: 8.0 },
      { sector: "Consumer Staples", weight: 6.5 },
      { sector: "Other", weight: 8.0 },
    ],
    distributionYield: 0.52,
    turnoverRate: 29,
    shariahCertification: "Yasaar Limited Certified",
    riskLevel: "Moderate",
    investorType: "Core US Equity Allocation",
    top10Concentration: 56.96,
    prospectusUrl: "https://funds.wahedinvest.com/",
    brokers: [
      { name: "Fidelity", countries: ["US"], url: "https://www.fidelity.com", commission: "$0" },
      { name: "Charles Schwab", countries: ["US"], url: "https://www.schwab.com", commission: "$0" },
      { name: "Interactive Brokers", countries: ["US", "UK", "CA", "EU"], url: "https://www.interactivebrokers.com", commission: "$0-$1" },
      { name: "Robinhood", countries: ["US"], url: "https://www.robinhood.com", commission: "$0" },
    ],
  },
  {
    ticker: "MNZL",
    name: "Manzil Russell Halal USA Broad Market ETF",
    focus: "US Large/Mid Blend",
    listing: "US",
    listingFlag: "US",
    expenseRatio: 0.40,
    aum: "$125M",
    inceptionDate: "Nov 2025",
    provider: "Manzil",
    benchmark: "Russell IdealRatings Manzil Halal USA Broad Market Index",
    description: "The newest and lowest cost US Halal ETF. MNZL offers broad exposure to large- and mid-cap U.S. equities through a framework extending beyond traditional Shariah screening, also applying American Friends Service Committee (AFSC) ethical filters for enhanced screening.",
    riskLevel: "Moderate",
    investorType: "Value-Conscious Core US Allocation",
    holdings: [
      { ticker: "AAPL", name: "Apple Inc", weight: 15.43, sector: "Technology" },
      { ticker: "AVGO", name: "Broadcom Inc", weight: 7.07, sector: "Technology" },
      { ticker: "GOOGL", name: "Alphabet Inc Class A", weight: 5.66, sector: "Technology" },
      { ticker: "TSLA", name: "Tesla Inc", weight: 4.71, sector: "Consumer Cyclical" },
      { ticker: "LLY", name: "Eli Lilly and Company", weight: 3.06, sector: "Healthcare" },
      { ticker: "JNJ", name: "Johnson & Johnson", weight: 2.85, sector: "Healthcare" },
      { ticker: "ABBV", name: "AbbVie Inc", weight: 2.72, sector: "Healthcare" },
      { ticker: "ORCL", name: "Oracle Corporation", weight: 2.45, sector: "Technology" },
      { ticker: "AMD", name: "Advanced Micro Devices", weight: 2.32, sector: "Technology" },
      { ticker: "HD", name: "Home Depot Inc", weight: 2.18, sector: "Consumer Cyclical" },
      { ticker: "MRK", name: "Merck & Co Inc", weight: 2.05, sector: "Healthcare" },
      { ticker: "CRM", name: "Salesforce Inc", weight: 1.98, sector: "Technology" },
      { ticker: "ADBE", name: "Adobe Inc", weight: 1.85, sector: "Technology" },
      { ticker: "PEP", name: "PepsiCo Inc", weight: 1.72, sector: "Consumer Staples" },
      { ticker: "COST", name: "Costco Wholesale Corp", weight: 1.65, sector: "Consumer Staples" },
      { ticker: "TMO", name: "Thermo Fisher Scientific", weight: 1.58, sector: "Healthcare" },
      { ticker: "ACN", name: "Accenture Plc", weight: 1.48, sector: "Technology" },
      { ticker: "DHR", name: "Danaher Corporation", weight: 1.42, sector: "Healthcare" },
      { ticker: "QCOM", name: "QUALCOMM Inc", weight: 1.35, sector: "Technology" },
      { ticker: "TXN", name: "Texas Instruments Inc", weight: 1.28, sector: "Technology" },
    ],
    performance: {
      oneMonth: -0.28,
      threeMonth: 4.12,
      sixMonth: 12.85,
      ytd: 8.50,
      oneYear: 8.50,
      threeYear: null,
      fiveYear: null,
      tenYear: null,
      sinceInception: 8.50,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 42.0 },
      { sector: "Healthcare", weight: 15.0 },
      { sector: "Consumer Cyclical", weight: 12.0 },
      { sector: "Industrials", weight: 10.0 },
      { sector: "Consumer Staples", weight: 8.0 },
      { sector: "Other", weight: 13.0 },
    ],
    distributionYield: 0.38,
    turnoverRate: 12,
    shariahCertification: "AAOIFI + AFSC Certified",
    riskLevel: "Moderate",
    investorType: "Value-Conscious Core US Allocation",
    top10Concentration: 52.0,
    prospectusUrl: "https://www.manzil.ca/etf",
    brokers: [
      { name: "Fidelity", countries: ["US"], url: "https://www.fidelity.com", commission: "$0" },
      { name: "Interactive Brokers", countries: ["US", "CA"], url: "https://www.interactivebrokers.com", commission: "$0-$1" },
    ],
  },
  {
    ticker: "SPRE",
    name: "SP Funds S&P Global REIT Shariah ETF",
    focus: "Global Real Estate",
    listing: "US",
    listingFlag: "US",
    expenseRatio: 0.50,
    aum: "$190M",
    inceptionDate: "Dec 2020",
    provider: "SP Funds",
    benchmark: "S&P Global All Equity REIT Shariah Capped Index",
    description: "The ONLY Shariah-compliant global REIT ETF available. SPRE invests exclusively in real estate companies that produce consistent rental income. Excellent for income-seeking investors wanting real estate exposure without owning physical property.",
    riskLevel: "Moderate",
    investorType: "Income & Diversification",
    holdings: [
      { ticker: "PLD", name: "Prologis Inc", weight: 18.50, sector: "Industrial REIT" },
      { ticker: "EQIX", name: "Equinix Inc", weight: 15.20, sector: "Data Center REIT" },
      { ticker: "GMG.AX", name: "Goodman Group (Australia)", weight: 12.80, sector: "Industrial REIT" },
      { ticker: "AVB", name: "AvalonBay Communities Inc", weight: 10.50, sector: "Residential REIT" },
      { ticker: "ELS", name: "Equity LifeStyle Properties", weight: 8.20, sector: "Residential REIT" },
      { ticker: "WELL", name: "Welltower Inc", weight: 6.80, sector: "Healthcare REIT" },
      { ticker: "DLR", name: "Digital Realty Trust Inc", weight: 5.50, sector: "Data Center REIT" },
      { ticker: "MAA", name: "Mid-America Apartment", weight: 4.20, sector: "Residential REIT" },
      { ticker: "CPT", name: "Camden Property Trust", weight: 3.80, sector: "Residential REIT" },
      { ticker: "ESS", name: "Essex Property Trust Inc", weight: 3.20, sector: "Residential REIT" },
      { ticker: "UDR", name: "UDR Inc", weight: 2.85, sector: "Residential REIT" },
      { ticker: "ARE", name: "Alexandria Real Estate", weight: 2.45, sector: "Office REIT" },
      { ticker: "EXR", name: "Extra Space Storage Inc", weight: 2.15, sector: "Storage REIT" },
      { ticker: "LSI", name: "Life Storage Inc", weight: 1.85, sector: "Storage REIT" },
      { ticker: "CUBE", name: "CubeSmart", weight: 1.52, sector: "Storage REIT" },
    ],
    performance: {
      oneMonth: 1.25,
      threeMonth: 2.85,
      sixMonth: 8.45,
      ytd: 12.30,
      oneYear: 12.30,
      threeYear: 8.50,
      fiveYear: null,
      tenYear: null,
      sinceInception: 9.20,
    },
    sectorAllocation: [
      { sector: "Industrial REITs", weight: 32.0 },
      { sector: "Residential REITs", weight: 28.0 },
      { sector: "Data Center REITs", weight: 22.0 },
      { sector: "Healthcare REITs", weight: 10.0 },
      { sector: "Other REITs", weight: 8.0 },
    ],
    distributionYield: 4.10,
    turnoverRate: 18,
    shariahCertification: "AAOIFI Certified",
    riskLevel: "Moderate",
    investorType: "Income & Diversification",
    top10Concentration: 88.0,
    prospectusUrl: "https://www.sp-funds.com/spre/",
    brokers: [
      { name: "Fidelity", countries: ["US"], url: "https://www.fidelity.com", commission: "$0" },
      { name: "Charles Schwab", countries: ["US"], url: "https://www.schwab.com", commission: "$0" },
      { name: "Interactive Brokers", countries: ["US", "UK", "CA"], url: "https://www.interactivebrokers.com", commission: "$0-$1" },
    ],
  },
  {
    ticker: "SPSK",
    name: "SP Funds Dow Jones Global Sukuk ETF",
    focus: "Global Sukuk (Islamic Bonds)",
    listing: "US",
    listingFlag: "US",
    expenseRatio: 0.50,
    aum: "$460M",
    inceptionDate: "Dec 2019",
    provider: "SP Funds",
    benchmark: "Dow Jones Sukuk Total Return Index",
    description: "The ONLY Sukuk ETF in the United States. SPSK invests in Islamic financial certificates similar to bonds but structured to comply with Islamic law. Excellent for conservative investors seeking steady income with lower volatility than equities.",
    riskLevel: "Low",
    investorType: "Fixed Income / Conservative",
    holdings: [
      { ticker: "KSASUK", name: "Kingdom of Saudi Arabia Sukuk", weight: 12.50, sector: "Government" },
      { ticker: "SAGLOB", name: "SA Global Sukuk Ltd", weight: 10.80, sector: "Government" },
      { ticker: "SUCI2", name: "SUCI Second Investment Co", weight: 8.50, sector: "Government" },
      { ticker: "ISDB", name: "Islamic Development Bank Sukuk", weight: 7.20, sector: "Supranational" },
      { ticker: "ADNOCSUK", name: "ADNOC Murban Sukuk", weight: 6.80, sector: "Corporate" },
      { ticker: "QATARSUK", name: "Qatar Sovereign Sukuk", weight: 6.20, sector: "Government" },
      { ticker: "INDOSUK", name: "Republic of Indonesia Sukuk", weight: 5.50, sector: "Government" },
      { ticker: "MAYSUK", name: "Malaysia Sovereign Sukuk", weight: 5.20, sector: "Government" },
      { ticker: "DPWSUK", name: "DP World Crescent Ltd Sukuk", weight: 4.80, sector: "Corporate" },
      { ticker: "EMRSUK", name: "Emirates NBD Sukuk", weight: 4.50, sector: "Corporate" },
      { ticker: "MASRSUK", name: "Masraf Al Rayan Sukuk", weight: 4.20, sector: "Corporate" },
      { ticker: "DIBSUK", name: "Dubai Islamic Bank Sukuk", weight: 3.85, sector: "Corporate" },
      { ticker: "TURKSUK", name: "Turkey Sovereign Sukuk", weight: 3.50, sector: "Government" },
      { ticker: "IDBSUK2", name: "IDB Trust Services 2", weight: 3.25, sector: "Supranational" },
      { ticker: "OORSUK", name: "Ooredoo International Sukuk", weight: 2.95, sector: "Corporate" },
      { ticker: "AABORGSUK", name: "Abu Dhabi Islamic Bank Sukuk", weight: 2.65, sector: "Corporate" },
      { ticker: "ETISUK", name: "Etisalat Sukuk", weight: 2.35, sector: "Corporate" },
      { ticker: "KFHSUK", name: "Kuwait Finance House Sukuk", weight: 2.15, sector: "Corporate" },
      { ticker: "QIBSUK", name: "Qatar Islamic Bank Sukuk", weight: 1.85, sector: "Corporate" },
      { ticker: "ALBSUK", name: "Al Baraka Banking Sukuk", weight: 1.55, sector: "Corporate" },
    ],
    performance: {
      oneMonth: 0.35,
      threeMonth: 1.20,
      sixMonth: 2.85,
      ytd: 4.50,
      oneYear: 4.50,
      threeYear: 3.20,
      fiveYear: 2.80,
      tenYear: null,
      sinceInception: 3.10,
    },
    sectorAllocation: [
      { sector: "Corporate Sukuk", weight: 60.47 },
      { sector: "Government Sukuk", weight: 37.93 },
      { sector: "Cash & Other", weight: 1.60 },
    ],
    distributionYield: 4.85,
    turnoverRate: 25,
    shariahCertification: "AAOIFI Certified",
    riskLevel: "Low",
    investorType: "Fixed Income / Conservative",
    top10Concentration: 58.0,
    prospectusUrl: "https://www.sp-funds.com/spsk/",
    brokers: [
      { name: "Fidelity", countries: ["US"], url: "https://www.fidelity.com", commission: "$0" },
      { name: "Charles Schwab", countries: ["US"], url: "https://www.schwab.com", commission: "$0" },
      { name: "Interactive Brokers", countries: ["US", "UK", "CA"], url: "https://www.interactivebrokers.com", commission: "$0-$1" },
    ],
  },
  {
    ticker: "SPTE",
    name: "SP Funds S&P Global Technology ETF",
    focus: "Global Technology",
    listing: "US",
    listingFlag: "US",
    expenseRatio: 0.55,
    aum: "$93M",
    inceptionDate: "Dec 2023",
    provider: "SP Funds",
    benchmark: "S&P Global 1200 Shariah Information Technology Capped Index",
    description: "Pure technology sector play. SPTE tracks Shariah-compliant large-cap equity securities within the IT sector globally, with nearly 99% invested in technology companies. Best for growth-oriented investors bullish on tech.",
    riskLevel: "High",
    investorType: "Growth / Sector Exposure",
    holdings: [
      { ticker: "TSM", name: "Taiwan Semiconductor (ADR)", weight: 15.80, sector: "Semiconductors" },
      { ticker: "NVDA", name: "NVIDIA Corporation", weight: 14.20, sector: "Semiconductors" },
      { ticker: "MSFT", name: "Microsoft Corporation", weight: 12.50, sector: "Software" },
      { ticker: "AAPL", name: "Apple Inc", weight: 11.80, sector: "Hardware" },
      { ticker: "SAP", name: "SAP SE (Germany)", weight: 6.50, sector: "Software" },
      { ticker: "AVGO", name: "Broadcom Inc", weight: 5.80, sector: "Semiconductors" },
      { ticker: "8035.T", name: "Tokyo Electron Ltd (Japan)", weight: 4.20, sector: "Semiconductors" },
      { ticker: "SHOP", name: "Shopify Inc (Canada)", weight: 3.50, sector: "Software" },
      { ticker: "ASML", name: "ASML Holding NV (Netherlands)", weight: 3.20, sector: "Semiconductors" },
      { ticker: "AMD", name: "Advanced Micro Devices", weight: 2.80, sector: "Semiconductors" },
      { ticker: "INFY", name: "Infosys Ltd (India)", weight: 2.45, sector: "IT Services" },
      { ticker: "ADBE", name: "Adobe Inc", weight: 2.25, sector: "Software" },
      { ticker: "CRM", name: "Salesforce Inc", weight: 2.05, sector: "Software" },
      { ticker: "ORCL", name: "Oracle Corporation", weight: 1.85, sector: "Software" },
      { ticker: "INTC", name: "Intel Corporation", weight: 1.65, sector: "Semiconductors" },
      { ticker: "6758.T", name: "Sony Group Corp (Japan)", weight: 1.48, sector: "Hardware" },
      { ticker: "QCOM", name: "QUALCOMM Inc", weight: 1.35, sector: "Semiconductors" },
      { ticker: "TXN", name: "Texas Instruments Inc", weight: 1.22, sector: "Semiconductors" },
      { ticker: "NOW", name: "ServiceNow Inc", weight: 1.08, sector: "Software" },
      { ticker: "AMAT", name: "Applied Materials Inc", weight: 0.95, sector: "Semiconductors" },
    ],
    performance: {
      oneMonth: -1.25,
      threeMonth: 5.85,
      sixMonth: 18.45,
      ytd: 25.80,
      oneYear: 25.80,
      threeYear: 22.50,
      fiveYear: null,
      tenYear: null,
      sinceInception: 18.20,
    },
    sectorAllocation: [
      { sector: "Semiconductors", weight: 45.0 },
      { sector: "Software", weight: 28.0 },
      { sector: "Hardware", weight: 15.0 },
      { sector: "IT Services", weight: 8.0 },
      { sector: "Other", weight: 4.0 },
    ],
    distributionYield: 0.28,
    turnoverRate: 15,
    shariahCertification: "AAOIFI Certified",
    riskLevel: "High",
    investorType: "Growth / Sector Exposure",
  },
  {
    ticker: "SPWO",
    name: "SP Funds S&P World ETF",
    focus: "Global Ex-US Large Blend",
    listing: "US",
    listingFlag: "US",
    expenseRatio: 0.55,
    aum: "$107M",
    inceptionDate: "Dec 2023",
    provider: "SP Funds",
    benchmark: "S&P DM Ex-U.S. & EM 50/50 Shariah Index",
    description: "International diversification without US exposure. SPWO tracks Shariah-compliant companies in developed and emerging markets outside of the U.S., providing global diversification. Pairs well with SPUS or HLAL for complete global exposure.",
    riskLevel: "Moderate",
    investorType: "International Diversification",
    holdings: [
      { ticker: "TSM", name: "Taiwan Semiconductor (ADR)", weight: 12.50, sector: "Technology" },
      { ticker: "NOVO-B", name: "Novo Nordisk A/S (Denmark)", weight: 8.80, sector: "Healthcare" },
      { ticker: "NESN", name: "Nestle SA (Switzerland)", weight: 6.20, sector: "Consumer Staples" },
      { ticker: "PDD", name: "PDD Holdings Inc (China)", weight: 5.50, sector: "Consumer Cyclical" },
      { ticker: "AZN", name: "AstraZeneca PLC (UK)", weight: 4.80, sector: "Healthcare" },
      { ticker: "NVS", name: "Novartis AG (Switzerland)", weight: 4.20, sector: "Healthcare" },
      { ticker: "SAP", name: "SAP SE (Germany)", weight: 3.80, sector: "Technology" },
      { ticker: "ROG", name: "Roche Holding AG (Switzerland)", weight: 3.50, sector: "Healthcare" },
      { ticker: "INFY", name: "Infosys Ltd (India)", weight: 3.20, sector: "Technology" },
      { ticker: "TCS", name: "Tata Consultancy (India)", weight: 2.80, sector: "Technology" },
      { ticker: "ASML", name: "ASML Holding NV (Netherlands)", weight: 2.55, sector: "Technology" },
      { ticker: "SIE.DE", name: "Siemens AG (Germany)", weight: 2.35, sector: "Industrials" },
      { ticker: "RELIANCE", name: "Reliance Industries (India)", weight: 2.15, sector: "Energy" },
      { ticker: "MC.PA", name: "LVMH (France)", weight: 1.95, sector: "Consumer Cyclical" },
      { ticker: "BABA", name: "Alibaba Group (China)", weight: 1.78, sector: "Consumer Cyclical" },
      { ticker: "TM", name: "Toyota Motor Corp (Japan)", weight: 1.62, sector: "Consumer Cyclical" },
      { ticker: "SHOP", name: "Shopify Inc (Canada)", weight: 1.48, sector: "Technology" },
      { ticker: "RY", name: "Royal Bank of Canada", weight: 1.35, sector: "Financials" },
      { ticker: "005930", name: "Samsung Electronics (Korea)", weight: 1.25, sector: "Technology" },
      { ticker: "BHP", name: "BHP Group Ltd (Australia)", weight: 1.12, sector: "Materials" },
    ],
    performance: {
      oneMonth: 0.85,
      threeMonth: 4.25,
      sixMonth: 10.85,
      ytd: 14.50,
      oneYear: 14.50,
      threeYear: 12.20,
      fiveYear: null,
      tenYear: null,
      sinceInception: 11.80,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 31.39 },
      { sector: "Healthcare", weight: 19.32 },
      { sector: "Industrials", weight: 14.71 },
      { sector: "Consumer Cyclical", weight: 12.43 },
      { sector: "Consumer Staples", weight: 10.15 },
      { sector: "Other", weight: 12.0 },
    ],
    distributionYield: 1.85,
    turnoverRate: 22,
    shariahCertification: "AAOIFI Certified",
    riskLevel: "Moderate",
    investorType: "International Diversification",
  },
  {
    ticker: "UMMA",
    name: "Wahed Dow Jones Islamic World ETF",
    focus: "Global Ex-US Large Growth",
    listing: "US",
    listingFlag: "US",
    expenseRatio: 0.65,
    aum: "$199M",
    inceptionDate: "Apr 2021",
    provider: "Wahed Invest",
    benchmark: "Dow Jones Islamic Market World ex-US Index",
    description: "Concentrated international portfolio. UMMA provides exposure to the 95 largest Shariah-compliant companies outside of the U.S., representing 21 nations across established markets. More concentrated than SPWO with focus on quality companies.",
    riskLevel: "Moderate",
    investorType: "International Diversification",
    holdings: [
      { ticker: "TSM", name: "Taiwan Semiconductor (ADR)", weight: 14.20, sector: "Technology" },
      { ticker: "NOVO-B", name: "Novo Nordisk A/S (Denmark)", weight: 9.50, sector: "Healthcare" },
      { ticker: "ASML", name: "ASML Holding N.V. (Netherlands)", weight: 7.80, sector: "Technology" },
      { ticker: "IFX", name: "Infineon Technologies AG (Germany)", weight: 5.20, sector: "Technology" },
      { ticker: "SHOP", name: "Shopify Inc (Canada)", weight: 4.80, sector: "Technology" },
      { ticker: "NVS", name: "Novartis AG (Switzerland)", weight: 4.50, sector: "Healthcare" },
      { ticker: "SAP", name: "SAP SE (Germany)", weight: 4.20, sector: "Technology" },
      { ticker: "ROG", name: "Roche Holding AG (Switzerland)", weight: 3.80, sector: "Healthcare" },
      { ticker: "NESN", name: "Nestle S.A. (Switzerland)", weight: 3.50, sector: "Consumer Staples" },
      { ticker: "TTE", name: "TotalEnergies SE (France)", weight: 3.20, sector: "Energy" },
      { ticker: "AZN", name: "AstraZeneca PLC (UK)", weight: 2.95, sector: "Healthcare" },
      { ticker: "INFY", name: "Infosys Ltd (India)", weight: 2.68, sector: "Technology" },
      { ticker: "SIE.DE", name: "Siemens AG (Germany)", weight: 2.45, sector: "Industrials" },
      { ticker: "8035.T", name: "Tokyo Electron Ltd (Japan)", weight: 2.25, sector: "Technology" },
      { ticker: "ENI.MI", name: "Eni S.p.A. (Italy)", weight: 2.05, sector: "Energy" },
      { ticker: "TCS", name: "Tata Consultancy (India)", weight: 1.88, sector: "Technology" },
      { ticker: "AIR.PA", name: "Airbus SE (France)", weight: 1.72, sector: "Industrials" },
      { ticker: "OR.PA", name: "L'Oreal SA (France)", weight: 1.58, sector: "Consumer Staples" },
      { ticker: "005930", name: "Samsung Electronics (Korea)", weight: 1.45, sector: "Technology" },
      { ticker: "RIO", name: "Rio Tinto PLC (UK)", weight: 1.32, sector: "Materials" },
    ],
    performance: {
      oneMonth: 1.15,
      threeMonth: 5.45,
      sixMonth: 12.25,
      ytd: 16.80,
      oneYear: 16.80,
      threeYear: 10.50,
      fiveYear: null,
      tenYear: null,
      sinceInception: 9.85,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 35.6 },
      { sector: "Healthcare", weight: 22.5 },
      { sector: "Consumer Staples", weight: 12.8 },
      { sector: "Industrials", weight: 11.2 },
      { sector: "Energy", weight: 8.5 },
      { sector: "Other", weight: 9.4 },
    ],
    distributionYield: 1.25,
    turnoverRate: 32,
    shariahCertification: "Yasaar Limited Certified",
    riskLevel: "Moderate",
    investorType: "International Diversification",
  },
  {
    ticker: "WSHR",
    name: "Wealthsimple Shariah World Equity Index ETF",
    focus: "Global Large Blend (Quality)",
    listing: "CA",
    listingFlag: "CA",
    expenseRatio: 0.50,
    aum: "$423M CAD",
    inceptionDate: "May 2021",
    provider: "Wealthsimple",
    benchmark: "Dow Jones Islamic Market Developed Markets Quality & Low Volatility Index",
    description: "Canada's first Shariah-compliant ETF with a quality/low volatility focus. Best for Canadian investors seeking global diversification with potentially more stable returns through quality and low volatility factors.",
    riskLevel: "Low",
    investorType: "Conservative / Quality Focus",
    holdings: [
      { ticker: "BARN", name: "Barry Callebaut AG (Switzerland)", weight: 5.80, sector: "Consumer Staples" },
      { ticker: "KO", name: "The Coca-Cola Company", weight: 5.50, sector: "Consumer Staples" },
      { ticker: "NESN", name: "Nestle S.A. (Switzerland)", weight: 5.20, sector: "Consumer Staples" },
      { ticker: "NVS", name: "Novartis AG (Switzerland)", weight: 4.80, sector: "Healthcare" },
      { ticker: "TRI", name: "Thomson Reuters Corp (Canada)", weight: 4.50, sector: "Industrials" },
      { ticker: "PEP", name: "PepsiCo, Inc.", weight: 4.20, sector: "Consumer Staples" },
      { ticker: "SCMN", name: "Swisscom AG (Switzerland)", weight: 3.80, sector: "Communication" },
      { ticker: "DOL", name: "Dollarama Inc (Canada)", weight: 3.50, sector: "Consumer Cyclical" },
      { ticker: "JNJ", name: "Johnson & Johnson", weight: 3.20, sector: "Healthcare" },
      { ticker: "UL", name: "Unilever PLC (UK)", weight: 3.00, sector: "Consumer Staples" },
      { ticker: "PG", name: "Procter & Gamble Co", weight: 2.85, sector: "Consumer Staples" },
      { ticker: "ABT", name: "Abbott Laboratories", weight: 2.68, sector: "Healthcare" },
      { ticker: "COST", name: "Costco Wholesale Corp", weight: 2.52, sector: "Consumer Staples" },
      { ticker: "MCD", name: "McDonald's Corporation", weight: 2.38, sector: "Consumer Cyclical" },
      { ticker: "CNR", name: "Canadian National Railway", weight: 2.25, sector: "Industrials" },
      { ticker: "RY", name: "Royal Bank of Canada", weight: 2.12, sector: "Financials" },
      { ticker: "ENB", name: "Enbridge Inc (Canada)", weight: 1.98, sector: "Energy" },
      { ticker: "OTIS", name: "Otis Worldwide Corp", weight: 1.85, sector: "Industrials" },
      { ticker: "DG", name: "Dollar General Corp", weight: 1.72, sector: "Consumer Staples" },
      { ticker: "SYY", name: "Sysco Corporation", weight: 1.58, sector: "Consumer Staples" },
    ],
    performance: {
      oneMonth: 0.65,
      threeMonth: 2.85,
      sixMonth: 7.45,
      ytd: 10.20,
      oneYear: 10.20,
      threeYear: 8.50,
      fiveYear: null,
      tenYear: null,
      sinceInception: 7.85,
    },
    sectorAllocation: [
      { sector: "Consumer Staples", weight: 16.8 },
      { sector: "Technology", weight: 16.4 },
      { sector: "Healthcare", weight: 13.6 },
      { sector: "Industrials", weight: 12.5 },
      { sector: "Communication Services", weight: 10.2 },
      { sector: "Other", weight: 30.5 },
    ],
    distributionYield: 1.38,
    turnoverRate: 18,
    shariahCertification: "Rating Intelligence Certified",
    riskLevel: "Low",
    investorType: "Conservative / Quality Focus",
  },
  {
    ticker: "ISWD",
    name: "iShares MSCI World Islamic UCITS ETF",
    focus: "Global Large Blend",
    listing: "UK",
    listingFlag: "UK",
    expenseRatio: 0.30,
    aum: "$936M",
    inceptionDate: "Dec 2007",
    provider: "BlackRock",
    benchmark: "MSCI World Islamic Index",
    description: "The oldest and most established Shariah-compliant ETF globally with the LOWEST expense ratio (0.30%). Provides broad exposure to international developed market equities. The gold standard for cost-conscious Halal investors.",
    riskLevel: "Moderate",
    investorType: "Core Global Allocation",
    holdings: [
      { ticker: "MSFT", name: "Microsoft Corporation", weight: 12.50, sector: "Technology" },
      { ticker: "TSLA", name: "Tesla Inc", weight: 8.20, sector: "Consumer Cyclical" },
      { ticker: "XOM", name: "Exxon Mobil Corporation", weight: 5.80, sector: "Energy" },
      { ticker: "PG", name: "Procter & Gamble Co", weight: 4.50, sector: "Consumer Staples" },
      { ticker: "JNJ", name: "Johnson & Johnson", weight: 4.20, sector: "Healthcare" },
      { ticker: "AMD", name: "Advanced Micro Devices", weight: 3.80, sector: "Technology" },
      { ticker: "CVX", name: "Chevron Corporation", weight: 3.50, sector: "Energy" },
      { ticker: "ADBE", name: "Adobe Inc", weight: 3.20, sector: "Technology" },
      { ticker: "CRM", name: "Salesforce Inc", weight: 2.80, sector: "Technology" },
      { ticker: "AZN", name: "AstraZeneca PLC (UK)", weight: 2.50, sector: "Healthcare" },
      { ticker: "PEP", name: "PepsiCo Inc", weight: 2.35, sector: "Consumer Staples" },
      { ticker: "MRK", name: "Merck & Co Inc", weight: 2.18, sector: "Healthcare" },
      { ticker: "COST", name: "Costco Wholesale Corp", weight: 2.05, sector: "Consumer Staples" },
      { ticker: "NVS", name: "Novartis AG (Switzerland)", weight: 1.92, sector: "Healthcare" },
      { ticker: "NESN", name: "Nestle SA (Switzerland)", weight: 1.78, sector: "Consumer Staples" },
      { ticker: "SAP", name: "SAP SE (Germany)", weight: 1.65, sector: "Technology" },
      { ticker: "ROG", name: "Roche Holding AG (Switzerland)", weight: 1.52, sector: "Healthcare" },
      { ticker: "TTE", name: "TotalEnergies SE (France)", weight: 1.42, sector: "Energy" },
      { ticker: "LLY", name: "Eli Lilly and Company", weight: 1.35, sector: "Healthcare" },
      { ticker: "UNH", name: "UnitedHealth Group Inc", weight: 1.28, sector: "Healthcare" },
    ],
    performance: {
      oneMonth: 0.45,
      threeMonth: 3.65,
      sixMonth: 12.85,
      ytd: 16.50,
      oneYear: 16.50,
      threeYear: 18.20,
      fiveYear: 14.80,
      tenYear: 11.50,
      sinceInception: 10.50,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 37.24 },
      { sector: "Healthcare", weight: 14.5 },
      { sector: "Energy", weight: 12.8 },
      { sector: "Consumer Staples", weight: 10.2 },
      { sector: "Industrials", weight: 9.5 },
      { sector: "Other", weight: 15.76 },
    ],
    distributionYield: 0.95,
    turnoverRate: 15,
    shariahCertification: "MSCI Islamic Index Certified",
    riskLevel: "Moderate",
    investorType: "Core Global Allocation",
  },
  {
    ticker: "ISDE",
    name: "iShares MSCI Emerging Markets Islamic UCITS ETF",
    focus: "Emerging Markets Growth",
    listing: "UK",
    listingFlag: "UK",
    expenseRatio: 0.35,
    aum: "$404M",
    inceptionDate: "Nov 2007",
    provider: "BlackRock",
    benchmark: "MSCI Emerging Markets Islamic Index",
    description: "The premier emerging markets Halal ETF with 300+ holdings. Provides Shariah-compliant exposure to emerging markets across the world with strong technology focus. Essential for investors seeking growth from developing economies.",
    riskLevel: "High",
    investorType: "Emerging Markets Exposure",
    holdings: [
      { ticker: "TSM", name: "Taiwan Semiconductor (ADR)", weight: 18.50, sector: "Technology" },
      { ticker: "005930", name: "Samsung Electronics (Korea)", weight: 12.80, sector: "Technology" },
      { ticker: "RELIANCE", name: "Reliance Industries (India)", weight: 6.50, sector: "Energy" },
      { ticker: "VALE3", name: "Vale S.A. (Brazil)", weight: 5.20, sector: "Materials" },
      { ticker: "1120.SR", name: "Al Rajhi Bank (Saudi Arabia)", weight: 4.80, sector: "Financials" },
      { ticker: "005935", name: "Samsung Electronics Pref (Korea)", weight: 4.20, sector: "Technology" },
      { ticker: "PETR4", name: "Petroleo Brasileiro (Brazil)", weight: 3.80, sector: "Energy" },
      { ticker: "HINDUNILVR", name: "Hindustan Unilever (India)", weight: 3.50, sector: "Consumer Staples" },
      { ticker: "000270", name: "Kia Corporation (Korea)", weight: 3.20, sector: "Consumer Cyclical" },
      { ticker: "TCS", name: "Tata Consultancy (India)", weight: 2.80, sector: "Technology" },
      { ticker: "INFY", name: "Infosys Ltd (India)", weight: 2.55, sector: "Technology" },
      { ticker: "2330.TW", name: "TSMC (Taiwan Direct)", weight: 2.35, sector: "Technology" },
      { ticker: "PDD", name: "PDD Holdings Inc (China)", weight: 2.18, sector: "Consumer Cyclical" },
      { ticker: "2317.TW", name: "Hon Hai Precision (Taiwan)", weight: 1.95, sector: "Technology" },
      { ticker: "SBIN", name: "State Bank of India", weight: 1.78, sector: "Financials" },
      { ticker: "HDFCBANK", name: "HDFC Bank Ltd (India)", weight: 1.62, sector: "Financials" },
      { ticker: "ARAMCO", name: "Saudi Aramco (Saudi Arabia)", weight: 1.48, sector: "Energy" },
      { ticker: "BABA", name: "Alibaba Group (China)", weight: 1.35, sector: "Consumer Cyclical" },
      { ticker: "2454.TW", name: "MediaTek Inc (Taiwan)", weight: 1.22, sector: "Technology" },
      { ticker: "STC", name: "Saudi Telecom Co (Saudi Arabia)", weight: 1.08, sector: "Communication" },
    ],
    performance: {
      oneMonth: 1.85,
      threeMonth: 6.25,
      sixMonth: 14.50,
      ytd: 18.20,
      oneYear: 18.20,
      threeYear: 8.50,
      fiveYear: 6.80,
      tenYear: 5.20,
      sinceInception: 5.20,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 41.53 },
      { sector: "Materials", weight: 12.5 },
      { sector: "Financials", weight: 10.8 },
      { sector: "Energy", weight: 9.5 },
      { sector: "Consumer Staples", weight: 8.2 },
      { sector: "Other", weight: 17.47 },
    ],
    distributionYield: 2.15,
    turnoverRate: 22,
    shariahCertification: "MSCI Islamic Index Certified",
    riskLevel: "High",
    investorType: "Emerging Markets Exposure",
  },
  {
    ticker: "IGDA",
    name: "Invesco Dow Jones Islamic Global Developed Markets UCITS ETF",
    focus: "Global Developed Markets",
    listing: "UK",
    listingFlag: "UK",
    expenseRatio: 0.40,
    aum: "$1.13B",
    inceptionDate: "Jun 2014",
    provider: "Invesco",
    benchmark: "Dow Jones Islamic Market Developed Markets Index",
    description: "Well-diversified developed markets exposure. Provides exposure to Shariah-compliant equities in developed markets with a strong tilt towards large-cap growth stocks. Alternative to ISWD with Dow Jones methodology.",
    riskLevel: "Moderate",
    investorType: "Core Global Allocation",
    holdings: [
      { ticker: "MSFT", name: "Microsoft Corporation", weight: 10.20, sector: "Technology" },
      { ticker: "AAPL", name: "Apple Inc", weight: 9.80, sector: "Technology" },
      { ticker: "NVDA", name: "NVIDIA Corporation", weight: 8.50, sector: "Technology" },
      { ticker: "AMZN", name: "Amazon.com Inc", weight: 5.80, sector: "Consumer Cyclical" },
      { ticker: "META", name: "Meta Platforms Inc", weight: 4.50, sector: "Technology" },
      { ticker: "GOOGL", name: "Alphabet Inc Class A", weight: 4.20, sector: "Technology" },
      { ticker: "TSLA", name: "Tesla Inc", weight: 3.80, sector: "Consumer Cyclical" },
      { ticker: "AVGO", name: "Broadcom Inc", weight: 3.20, sector: "Technology" },
      { ticker: "TSM", name: "Taiwan Semiconductor (ADR)", weight: 2.80, sector: "Technology" },
      { ticker: "NOVO-B", name: "Novo Nordisk A/S (Denmark)", weight: 2.50, sector: "Healthcare" },
      { ticker: "ASML", name: "ASML Holding NV (Netherlands)", weight: 2.28, sector: "Technology" },
      { ticker: "JNJ", name: "Johnson & Johnson", weight: 2.05, sector: "Healthcare" },
      { ticker: "PG", name: "Procter & Gamble Co", weight: 1.88, sector: "Consumer Staples" },
      { ticker: "XOM", name: "Exxon Mobil Corporation", weight: 1.72, sector: "Energy" },
      { ticker: "LLY", name: "Eli Lilly and Company", weight: 1.58, sector: "Healthcare" },
      { ticker: "NVS", name: "Novartis AG (Switzerland)", weight: 1.45, sector: "Healthcare" },
      { ticker: "SAP", name: "SAP SE (Germany)", weight: 1.32, sector: "Technology" },
      { ticker: "MRK", name: "Merck & Co Inc", weight: 1.22, sector: "Healthcare" },
      { ticker: "NESN", name: "Nestle SA (Switzerland)", weight: 1.12, sector: "Consumer Staples" },
      { ticker: "CVX", name: "Chevron Corporation", weight: 1.05, sector: "Energy" },
    ],
    performance: {
      oneMonth: -0.15,
      threeMonth: 4.85,
      sixMonth: 15.20,
      ytd: 20.50,
      oneYear: 20.50,
      threeYear: 18.80,
      fiveYear: null,
      tenYear: null,
      sinceInception: 16.20,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 39.22 },
      { sector: "Healthcare", weight: 15.33 },
      { sector: "Consumer Cyclical", weight: 11.17 },
      { sector: "Communication Services", weight: 9.5 },
      { sector: "Industrials", weight: 8.2 },
      { sector: "Other", weight: 16.58 },
    ],
    distributionYield: 0.72,
    turnoverRate: 18,
    shariahCertification: "Dow Jones Islamic Market Certified",
    riskLevel: "Moderate",
    investorType: "Core Global Allocation",
  },
  {
    ticker: "ISDU",
    name: "iShares MSCI USA Islamic UCITS ETF",
    focus: "US Large Cap Blend",
    listing: "UK",
    listingFlag: "UK",
    expenseRatio: 0.30,
    aum: "$310M",
    inceptionDate: "Dec 2007",
    provider: "BlackRock",
    benchmark: "MSCI USA Islamic Index",
    description: "Low-cost exposure to US equities via the UK market. ISDU tracks the MSCI USA Islamic Index, providing Shariah-compliant exposure to large and mid-cap US companies. One of the lowest expense ratios available for Halal ETFs.",
    riskLevel: "Moderate",
    investorType: "Core US Allocation",
    holdings: [
      { ticker: "MSFT", name: "Microsoft Corporation", weight: 13.50, sector: "Technology" },
      { ticker: "TSLA", name: "Tesla Inc", weight: 8.80, sector: "Consumer Cyclical" },
      { ticker: "XOM", name: "Exxon Mobil Corporation", weight: 6.20, sector: "Energy" },
      { ticker: "PG", name: "Procter & Gamble Co", weight: 4.80, sector: "Consumer Staples" },
      { ticker: "JNJ", name: "Johnson & Johnson", weight: 4.50, sector: "Healthcare" },
      { ticker: "AMD", name: "Advanced Micro Devices", weight: 4.10, sector: "Technology" },
      { ticker: "CVX", name: "Chevron Corporation", weight: 3.80, sector: "Energy" },
      { ticker: "ADBE", name: "Adobe Inc", weight: 3.40, sector: "Technology" },
      { ticker: "CRM", name: "Salesforce Inc", weight: 3.00, sector: "Technology" },
      { ticker: "PEP", name: "PepsiCo Inc", weight: 2.60, sector: "Consumer Staples" },
      { ticker: "LLY", name: "Eli Lilly and Company", weight: 2.45, sector: "Healthcare" },
      { ticker: "COST", name: "Costco Wholesale Corp", weight: 2.30, sector: "Consumer Staples" },
      { ticker: "MRK", name: "Merck & Co Inc", weight: 2.15, sector: "Healthcare" },
      { ticker: "ABBV", name: "AbbVie Inc", weight: 2.00, sector: "Healthcare" },
      { ticker: "UNH", name: "UnitedHealth Group Inc", weight: 1.88, sector: "Healthcare" },
      { ticker: "ORCL", name: "Oracle Corporation", weight: 1.75, sector: "Technology" },
      { ticker: "DHR", name: "Danaher Corporation", weight: 1.62, sector: "Healthcare" },
      { ticker: "QCOM", name: "QUALCOMM Inc", weight: 1.50, sector: "Technology" },
      { ticker: "TXN", name: "Texas Instruments Inc", weight: 1.40, sector: "Technology" },
      { ticker: "NFLX", name: "Netflix Inc", weight: 1.28, sector: "Communication" },
    ],
    performance: {
      oneMonth: 0.35,
      threeMonth: 3.45,
      sixMonth: 12.50,
      ytd: 15.80,
      oneYear: 15.80,
      threeYear: 16.50,
      fiveYear: 13.20,
      tenYear: 10.80,
      sinceInception: 9.50,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 35.0 },
      { sector: "Healthcare", weight: 15.5 },
      { sector: "Energy", weight: 13.0 },
      { sector: "Consumer Staples", weight: 11.5 },
      { sector: "Consumer Cyclical", weight: 10.0 },
      { sector: "Other", weight: 15.0 },
    ],
    distributionYield: 0.88,
    turnoverRate: 14,
    shariahCertification: "MSCI Islamic Index Certified",
  },
  {
    ticker: "HIUS",
    name: "HSBC MSCI USA Islamic ESG UCITS ETF",
    focus: "US Large Cap ESG",
    listing: "UK",
    listingFlag: "UK",
    expenseRatio: 0.30,
    aum: "$150M",
    inceptionDate: "Nov 2022",
    provider: "HSBC",
    benchmark: "MSCI USA Custom Islamic Universal ESG Screened Index",
    description: "Combines Shariah compliance with ESG factors. HIUS provides exposure to US companies that meet both Islamic principles and ESG (Environmental, Social, Governance) criteria. Ideal for socially conscious Muslim investors.",
    riskLevel: "Moderate",
    investorType: "ESG-Focused US Allocation",
    holdings: [
      { ticker: "MSFT", name: "Microsoft Corporation", weight: 14.20, sector: "Technology" },
      { ticker: "AAPL", name: "Apple Inc", weight: 11.50, sector: "Technology" },
      { ticker: "GOOGL", name: "Alphabet Inc Class A", weight: 7.80, sector: "Technology" },
      { ticker: "TSLA", name: "Tesla Inc", weight: 6.50, sector: "Consumer Cyclical" },
      { ticker: "JNJ", name: "Johnson & Johnson", weight: 4.20, sector: "Healthcare" },
      { ticker: "PG", name: "Procter & Gamble Co", weight: 3.80, sector: "Consumer Staples" },
      { ticker: "XOM", name: "Exxon Mobil Corporation", weight: 3.50, sector: "Energy" },
      { ticker: "HD", name: "Home Depot Inc", weight: 3.20, sector: "Consumer Cyclical" },
      { ticker: "LLY", name: "Eli Lilly and Company", weight: 2.95, sector: "Healthcare" },
      { ticker: "MRK", name: "Merck & Co Inc", weight: 2.70, sector: "Healthcare" },
      { ticker: "PEP", name: "PepsiCo Inc", weight: 2.45, sector: "Consumer Staples" },
      { ticker: "COST", name: "Costco Wholesale Corp", weight: 2.20, sector: "Consumer Staples" },
      { ticker: "ABBV", name: "AbbVie Inc", weight: 2.05, sector: "Healthcare" },
      { ticker: "CRM", name: "Salesforce Inc", weight: 1.90, sector: "Technology" },
      { ticker: "ADBE", name: "Adobe Inc", weight: 1.78, sector: "Technology" },
      { ticker: "ACN", name: "Accenture Plc", weight: 1.65, sector: "Technology" },
      { ticker: "DHR", name: "Danaher Corporation", weight: 1.52, sector: "Healthcare" },
      { ticker: "TXN", name: "Texas Instruments Inc", weight: 1.42, sector: "Technology" },
      { ticker: "QCOM", name: "QUALCOMM Inc", weight: 1.32, sector: "Technology" },
      { ticker: "INTC", name: "Intel Corporation", weight: 1.22, sector: "Technology" },
    ],
    performance: {
      oneMonth: 0.42,
      threeMonth: 3.85,
      sixMonth: 13.20,
      ytd: 17.50,
      oneYear: 17.50,
      threeYear: null,
      fiveYear: null,
      tenYear: null,
      sinceInception: 14.80,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 42.0 },
      { sector: "Healthcare", weight: 16.0 },
      { sector: "Consumer Staples", weight: 12.0 },
      { sector: "Consumer Cyclical", weight: 10.0 },
      { sector: "Energy", weight: 8.0 },
      { sector: "Other", weight: 12.0 },
    ],
    distributionYield: 0.75,
    turnoverRate: 12,
    shariahCertification: "MSCI Islamic + ESG Certified",
  },
  {
    ticker: "HIES",
    name: "HSBC MSCI Emerging Markets Islamic ESG UCITS ETF",
    focus: "Emerging Markets ESG",
    listing: "UK",
    listingFlag: "UK",
    expenseRatio: 0.35,
    aum: "$85M",
    inceptionDate: "Jan 2023",
    provider: "HSBC",
    benchmark: "MSCI Emerging Markets Custom Islamic Universal ESG Screened Index",
    description: "ESG-focused emerging markets exposure with Shariah compliance. HIES invests in companies across 24 emerging market countries that meet both Islamic principles and ESG standards. Perfect for growth-oriented ethical investors.",
    riskLevel: "High",
    investorType: "ESG-Focused Emerging Markets",
    holdings: [
      { ticker: "TSM", name: "Taiwan Semiconductor (ADR)", weight: 16.50, sector: "Technology" },
      { ticker: "005930", name: "Samsung Electronics (Korea)", weight: 11.20, sector: "Technology" },
      { ticker: "RELIANCE", name: "Reliance Industries (India)", weight: 5.80, sector: "Energy" },
      { ticker: "TCS", name: "Tata Consultancy (India)", weight: 4.50, sector: "Technology" },
      { ticker: "INFY", name: "Infosys Ltd (India)", weight: 4.20, sector: "Technology" },
      { ticker: "VALE3", name: "Vale S.A. (Brazil)", weight: 3.80, sector: "Materials" },
      { ticker: "HINDUNILVR", name: "Hindustan Unilever (India)", weight: 3.50, sector: "Consumer Staples" },
      { ticker: "PETR4", name: "Petroleo Brasileiro (Brazil)", weight: 3.20, sector: "Energy" },
      { ticker: "PDD", name: "PDD Holdings Inc (China)", weight: 2.90, sector: "Consumer Cyclical" },
      { ticker: "2330.TW", name: "TSMC (Taiwan Direct)", weight: 2.65, sector: "Technology" },
      { ticker: "2317.TW", name: "Hon Hai Precision (Taiwan)", weight: 2.40, sector: "Technology" },
      { ticker: "000270", name: "Kia Corporation (Korea)", weight: 2.18, sector: "Consumer Cyclical" },
      { ticker: "SBIN", name: "State Bank of India", weight: 1.95, sector: "Financials" },
      { ticker: "2454.TW", name: "MediaTek Inc (Taiwan)", weight: 1.75, sector: "Technology" },
      { ticker: "BABA", name: "Alibaba Group (China)", weight: 1.58, sector: "Consumer Cyclical" },
      { ticker: "1120.SR", name: "Al Rajhi Bank (Saudi Arabia)", weight: 1.42, sector: "Financials" },
      { ticker: "ARAMCO", name: "Saudi Aramco (Saudi Arabia)", weight: 1.28, sector: "Energy" },
      { ticker: "STC", name: "Saudi Telecom Co (Saudi Arabia)", weight: 1.15, sector: "Communication" },
      { ticker: "HDFCBANK", name: "HDFC Bank Ltd (India)", weight: 1.05, sector: "Financials" },
      { ticker: "LT", name: "Larsen & Toubro (India)", weight: 0.95, sector: "Industrials" },
    ],
    performance: {
      oneMonth: 1.65,
      threeMonth: 5.85,
      sixMonth: 13.20,
      ytd: 16.80,
      oneYear: 16.80,
      threeYear: null,
      fiveYear: null,
      tenYear: null,
      sinceInception: 12.50,
    },
    sectorAllocation: [
      { sector: "Technology", weight: 45.0 },
      { sector: "Energy", weight: 12.0 },
      { sector: "Materials", weight: 10.0 },
      { sector: "Consumer Cyclical", weight: 9.0 },
      { sector: "Financials", weight: 8.0 },
      { sector: "Other", weight: 16.0 },
    ],
    distributionYield: 1.85,
    turnoverRate: 18,
    shariahCertification: "MSCI Islamic + ESG Certified",
  },
  {
    ticker: "SKUK",
    name: "iShares $ Sukuk UCITS ETF",
    focus: "Emerging Markets Sukuk (Islamic Bonds)",
    listing: "EU",
    listingFlag: "EU",
    expenseRatio: 0.50,
    aum: "$720M",
    inceptionDate: "Nov 2019",
    provider: "BlackRock",
    benchmark: "J.P. Morgan EM Aggregate Sukuk Index",
    description: "Europe's premier Sukuk ETF. SKUK invests in US dollar-denominated sukuk bonds from emerging markets, adhering to Islamic principles. It provides exposure to the growing sukuk market while maintaining Shariah compliance. Excellent for European investors seeking fixed income alternatives.",
    riskLevel: "Low",
    investorType: "Fixed Income / Conservative",
    holdings: [
      { ticker: "KSASUK26", name: "Kingdom of Saudi Arabia 2026", weight: 8.50, sector: "Government" },
      { ticker: "KSASUK29", name: "Kingdom of Saudi Arabia 2029", weight: 7.80, sector: "Government" },
      { ticker: "QATSUK28", name: "State of Qatar Sukuk 2028", weight: 6.50, sector: "Government" },
      { ticker: "UAESUK27", name: "UAE Sovereign Sukuk 2027", weight: 5.80, sector: "Government" },
      { ticker: "INDOSUK30", name: "Indonesia Sukuk 2030", weight: 5.20, sector: "Government" },
      { ticker: "ISDB2025", name: "Islamic Development Bank 2025", weight: 4.80, sector: "Supranational" },
      { ticker: "ARAMCO28", name: "Saudi Aramco Sukuk 2028", weight: 4.50, sector: "Corporate" },
      { ticker: "DPWSUK29", name: "DP World Sukuk 2029", weight: 4.20, sector: "Corporate" },
      { ticker: "QIBSUK26", name: "Qatar Islamic Bank 2026", weight: 3.80, sector: "Corporate" },
      { ticker: "MAYSUK27", name: "Malaysia Sukuk 2027", weight: 3.50, sector: "Government" },
      { ticker: "ADNOC27", name: "ADNOC Murban Sukuk 2027", weight: 3.20, sector: "Corporate" },
      { ticker: "EMRSUK28", name: "Emirates NBD Sukuk 2028", weight: 2.95, sector: "Corporate" },
      { ticker: "TURKSUK26", name: "Turkey Sovereign Sukuk 2026", weight: 2.70, sector: "Government" },
      { ticker: "BAHSUK29", name: "Bahrain Sovereign Sukuk 2029", weight: 2.50, sector: "Government" },
      { ticker: "PAKISUK27", name: "Pakistan Sukuk 2027", weight: 2.30, sector: "Government" },
      { ticker: "ETISUK26", name: "Etisalat Sukuk 2026", weight: 2.10, sector: "Corporate" },
      { ticker: "KFHSUK28", name: "Kuwait Finance House 2028", weight: 1.95, sector: "Corporate" },
      { ticker: "DIBSUK27", name: "Dubai Islamic Bank 2027", weight: 1.80, sector: "Corporate" },
      { ticker: "OMANSUK30", name: "Oman Sovereign Sukuk 2030", weight: 1.65, sector: "Government" },
      { ticker: "MASRSUK26", name: "Masraf Al Rayan Sukuk 2026", weight: 1.50, sector: "Corporate" },
    ],
    performance: {
      oneMonth: 0.42,
      threeMonth: 1.35,
      sixMonth: 3.10,
      ytd: 4.85,
      oneYear: 4.85,
      threeYear: 3.50,
      fiveYear: 3.20,
      tenYear: null,
      sinceInception: 3.35,
    },
    sectorAllocation: [
      { sector: "Government Sukuk", weight: 48.5 },
      { sector: "Corporate Sukuk", weight: 40.2 },
      { sector: "Supranational", weight: 8.8 },
      { sector: "Cash & Other", weight: 2.5 },
    ],
    distributionYield: 5.10,
    turnoverRate: 20,
    shariahCertification: "AAOIFI Certified",
    riskLevel: "Low",
    investorType: "Fixed Income / Conservative",
    top10Concentration: 54.6,
    prospectusUrl: "https://www.ishares.com/uk/individual/en/products/309040/",
    brokers: [
      { name: "Interactive Brokers", countries: ["UK", "EU", "CA"], url: "https://www.interactivebrokers.com", commission: "€1-€3" },
      { name: "Saxo Bank", countries: ["UK", "EU"], url: "https://www.saxobank.com", commission: "€2-€5" },
      { name: "DEGIRO", countries: ["EU"], url: "https://www.degiro.com", commission: "€2" },
    ],
  },
]

export const etfCategories = [
  { id: "all", label: "All ETFs" },
  { id: "us", label: "US Equity" },
  { id: "global", label: "Global Equity" },
  { id: "emerging", label: "Emerging Markets" },
  { id: "fixed-income", label: "Fixed Income (Sukuk)" },
  { id: "real-estate", label: "Real Estate" },
  { id: "technology", label: "Technology" },
]

export function filterETFsByCategory(category: string): ETF[] {
  if (category === "all") return etfData
  if (category === "us") return etfData.filter(etf => etf.focus.includes("US") && !etf.focus.includes("Ex-US"))
  if (category === "global") return etfData.filter(etf => (etf.focus.includes("Global") || etf.focus.includes("Ex-US")) && !etf.focus.includes("Real Estate") && !etf.focus.includes("Technology"))
  if (category === "emerging") return etfData.filter(etf => etf.focus.includes("Emerging"))
  if (category === "fixed-income") return etfData.filter(etf => etf.focus.includes("Sukuk"))
  if (category === "real-estate") return etfData.filter(etf => etf.focus.includes("Real Estate"))
  if (category === "technology") return etfData.filter(etf => etf.focus.includes("Technology") && !etf.focus.includes("Ex-US") && !etf.focus.includes("Global Large"))
  return etfData
}

export function getRiskColor(risk: "Low" | "Moderate" | "High"): string {
  switch (risk) {
    case "Low": return "text-green-600"
    case "Moderate": return "text-yellow-600"
    case "High": return "text-red-600"
    default: return "text-muted-foreground"
  }
}
